name: "YouTube Downloader Bot"
description: "Telegram bot that downloads YouTube videos and sends them to chat"
version: "0.0.1"
slug: "yt-downloader-bot"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
options:
  bot_token: ""
  telegram_api_id: ""
  telegram_api_hash: ""
schema:
  bot_token: str
  telegram_api_id: str
  telegram_api_hash: str
